apiVersion: v1
kind: Pod
metadata:
  name: podexample
  labels:
    app: ustimage
spec:
  containers:
    - name: podcontainer
      image: rajcosivadevops/ustimage:latest
      ports:
        - containerPort: 80